services:
  unbound:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        UNBOUND_VERSION: ${UNBOUND_VERSION}
    image: jlevandowski/unbound:${ALPINE_VERSION}-${UNBOUND_VERSION}
