services:
  samba:
    container_name: samba
    hostname: samba
    image: ghcr.io/servercontainers/samba:latest
    restart: unless-stopped
    environment:
      ACCOUNT_john: ${john_password} #from .env file
      UID_username: 1000
      SAMBA_VOLUME_CONFIG_share: "[share]; path=/share; available = yes; browseable = yes; writable = yes; read only = no; force user = john; public = no; guest ok = no"
    volumes:
      - /share:/share
      - /etc/avahi/services/:/external/avahi
    ports:
      - 445:445
      - 139:139
      - 137:137/udp
    networks:
      samba_network:
        ipv4_address: '172.21.137.137'
    cap_add:
      - CAP_NET_ADMIN

networks:
  samba_network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.137.0/24
