services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION}
    network_mode: host
    environment:
      TZ: 'US/Mountain'
      # FTLCONF_dhcp_active: true # turn on DHCP server manually
      FTLCONF_dhcp_start: '192.168.0.201'
      FTLCONF_dhcp_end: '192.168.0.254'
      FTLCONF_dhcp_router: '192.168.0.1'
      FTLCONF_dhcp_leaseTime: '24h'
      FTLCONF_dns_domain: 'lan.johnl.dev'
      FTLCONF_dns_domainNeeded: 'true'
      FTLCONF_dns_expandHosts: 'true'
      FTLCONF_dns_piholePTR: 'HOSTNAMEFQDN'
      FTLCONF_dns_queryLogging: 'false'
      FTLCONF_dns_specialDomains_iCloudPrivateRelay: 'false'
      FTLCONF_dns_upstreams: '172.21.53.53'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_ntp_ipv4_active: 'false'
      FTLCONF_ntp_ipv6_active: 'false'
      FTLCONF_ntp_sync_active: 'false'
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password} #from .env file
      FTLCONF_webserver_domain: ${FTLCONF_webserver_domain}
      FTLCONF_webserver_port: 8080
      FTLCONF_webserver_session_timeout: 2592000
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './var-log-pihole:/var/log/pihole'
    cap_add:
       - NET_ADMIN
    restart: unless-stopped
    depends_on:
      unbound:
        condition: service_healthy

  unbound:
    container_name: unbound
    hostname: unbound
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        UNBOUND_VERSION: ${UNBOUND_VERSION}
    image: jlevandowski/unbound:${ALPINE_VERSION}-${UNBOUND_VERSION}
    volumes:
      - "./etc-unbound:/etc/unbound"
    cap_add:
       - NET_ADMIN
    restart: unless-stopped
    networks:
      unbound_network:
        ipv4_address: '172.21.53.53'

networks:
  unbound_network:
    external: true
